"""в User добавила колонку image_file

Revision ID: 2059f95bf175
Revises: 476763da83e3
Create Date: 2020-04-28 15:50:29.533852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2059f95bf175'
down_revision = '476763da83e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('image_file', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_image_file'), 'users', ['image_file'], unique=False)
    op.alter_column('users_words', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_words', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_image_file'), table_name='users')
    op.drop_column('users', 'image_file')
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
