"""tables for trainings

Revision ID: 90dff69375cb
Revises: 65ae67abbbb0
Create Date: 2020-04-19 18:32:13.884549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dff69375cb'
down_revision = '65ae67abbbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_words', sa.Column('memorizing_time', sa.DateTime(), nullable=True))
    op.add_column('users_words', sa.Column('word_translation', sa.Integer(), nullable=True))
    op.alter_column('users_words', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_words', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users_words', 'word_translation')
    op.drop_column('users_words', 'memorizing_time')
    # ### end Alembic commands ###
