"""еще одна попытка

Revision ID: cc91b38ce1dd
Revises: 57fde090b03d
Create Date: 2020-04-21 20:38:30.955871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc91b38ce1dd'
down_revision = '57fde090b03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users_words', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_words', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_foreign_key(None, 'teachers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    op.drop_table('teachers_students')
    # ### end Alembic commands ###
